- Makefile
- README.md
- docker-compose.common.yml
- docker-compose.cronjob.yml
- docker-compose.dispatchers.yml
- docker-compose.monitor.yml
- docker-compose.workers.yml
- docker-compose.yml
- lb/traefik.toml
> chore(postgres): disable ssh from postdock images due to updated

- Makefile
- README.md
- docker-compose.workers.yml
Eu e o @hudsama fizemos alguns ajustes para tornar o comando `make begin` mais leve e melhorar a forma de trabalho do comando `make migrate`.
> Feature making setup simpler

- Makefile
- docker-compose.common.yml
- docker-compose.yml
- Change order of start traefik and services
- Update traefik image to stable version
> Hotfix TRAEFIK start

- docker-compose.yml
Explicitando porta da api-v2 para funcionar no macOs.
> [api-v2] hotfix ports config to macos

- docker-compose.common.yml
- docker-compose.cronjob.yml
- docker-compose.monitor.yml
- docker-compose.workers.yml
- docker-compose.yml
Este PR resolve um problema em que não é possível acessar os serviços por conta do mapeamento dos mesmos em endereços de subnet. Erro ocasionado provavelmente por conta de algum problema de incompatibilidade de rede, ou algo do tipo
> fix(subnet): remove subnet networks of all services

- README.md
- docker-compose.apis.yml
**Contexto**
Esse PR faz atualizações ao arquivo README para que o setup inicial esteja atualizado com as práticas atuais.
> Updates on the README file

- .gitignore
- docker-compose.clients.yml
- docker-compose.listeners.yml
- docker-compose.pipelines.yml
- docker-compose.webhooks.yml
- docker-compose.yml
Pipeline: Flow data from one database table to other table or integration;
Listener: Websocket process updated data when occurs.
> feature(redes): Introduce pipeline and listeners

- Makefile
- docker-compose.plip.yml
> chore(infra): add docker-compose.plip.yml

- events/docker-compose.yml
PS: uma ideia seria padronizar melhor esa variável depois.
> Update version (1.7.2) of mapa's events 

- clients/docker-compose.yml
- common/docker-compose.yml
- remote-schemas/docker-compose.yml
- Corrige estrutura para certificados automatizados
- Atualiza pnpm para versão 7 nos `clients` e `remote-schemas`
> Release: Altera provedor de configuração do Traefik para etcd

- events/docker-compose.yml
Correção do comando de healthcheck do phone
> fix(events): fix command for phone healthcheck

- clients/docker-compose.yml
- https://github.com/nossas/bonde-clients/pull/1610
> release: update clients to v7.1.1

- events/docker-compose.yml
Configuração para reinicialização dos serviços no stack events
> chore(events): add restart configuration

- mapa/docker-compose.yml
Adicionar stack do mapa com mautic.
> chore(mapa): add mautic

- events/docker-compose.yml
atualizar versão dos eventos do mapa
> chore(events): update version mapa 1.7.5

- remote-schemas/docker-compose.yml
Atualizar api-data para  versão v1.3.7
> Atualizar api-data  v1.3.7

- remote-schemas/docker-compose.yml
update version remote-schemas to v1.3.9
> update version remote-schemas to v1.3.9

- common/docker-compose.yml
> chore: add N8N_USER_MANAGEMENT_DISABLED to n8n

- common/docker-compose.yml
> update version n8n to  1.16.0

- listeners/docker-compose.yml
Removendo os serviços de redes
> chore(listener): remove redes and redes-location
